stages:
  - docker

job_docker:
  stage: docker
  image: 
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
  - auth_value=$(echo -n nekeroo:$GITLAB_CI_DOCKER_PASSWORD | base64)
  - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$auth_value\"}}}" > /kaniko/.docker/config.json
  - cat /kaniko/.docker/config.json
  - /kaniko/executor 
      --context "./app-angular"
      --dockerfile "./app-angular/dockerfile"
      --destination "nekeroo/application-angular:latest"
  needs: []