# Stage 1: Builder
FROM node:20-alpine3.19 AS builder

# Définit le répertoire de travail
WORKDIR /app

# Copie les fichiers nécessaires
COPY . .

# Installe les dépendances
RUN npm ci

# Build l'application
RUN npm run build

# Stage 2: Final
FROM node:20-alpine3.19 AS final

# Définit le répertoire de travail
WORKDIR /app

# Copie le build de l'étape précédente
COPY --from=builder /app .

EXPOSE 4200

CMD ["npm", "run", "start"]