name: Angular CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: |
          npm install
        working-directory: ./app-angular
          
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: app-angular/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: lint
        run: |
          npm run lint
        working-directory: ./app-angular
      
      - name: audit
        run: |
          npm audit
        working-directory: ./app-angular
      
      - name: test
        run: |
          npm run test -- --browsers ChromeHeadlessNoSandbox
        working-directory: ./app-angular

        - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Docker credentials
        run: |
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n nekeroo:${{ secrets.GITLAB_CI_DOCKER_PASSWORD }} | base64)\"}}}" > $HOME/.docker/config.json
          cat $HOME/.docker/config.json

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --file ./app-angular/dockerfile \
            --tag nekeroo/application-angular:latest \
            --push \
            ./app-angular
